# This is a basic workflow to help you get started with Actions

name: Bleeding-Edge Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Setup Love2D
        run: |
          sudo add-apt-repository ppa:bartbes/love-stable
          sudo apt update
          sudo apt-get install love
      
      - name: Get Current Version
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Increase Version
        id: increase_version
        run: echo "::set-output name=version::$((${{ steps.get_version.outputs.version }} + 1))"
        
      - name: Update Version File
        run: echo "${{ steps.increase_version.outputs.version }}" > version.txt
        
      - name: Package
        run: love --version && love . --export "StationArchitect" --version "${{ steps.increase_version.outputs.version }}" --author "TheLife"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifact-build-bleeding
          path: StationArchitect.love
